apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pokemon-ingress
spec:
  rules:
  - host: game2048.poke-itcamp.xyz  # Ganti dengan nama domain Anda
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: game2048-svc
            port:
              number: 80  # Sesuaikan dengan port Service Anda jika berbeda
