apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: game2048-develop
bases:
  - "do-alb.yaml"
resources:
  - "../../service/config/overlays/develop"
  - "../../service/game2048/overlays/develop"